config/routes.rb
Rails.application.routes.draw do
  resources :channel_tags
  resources :preview_statuses
  resources :channel_statuses
  resources :channel_games
  get 'games/index'
  devise_for :users
  resources :channels
  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
  end

  root 'channels#index'
end

app/models/channel.rb
class Channel < ApplicationRecord
  belongs_to :user
  validates_uniqueness_of :user_id
  has_many :channel_game
  has_many :preview_statuses
  has_many :channel_tags
  has_many :channel_status
  attr_accessor :games
  attr_accessor :language
  attr_accessor :status
  attr_accessor :p_status
  attr_accessor :tags

  validates_presence_of :about
  validates_presence_of :language_id

  validates :title, presence: true, length: { maximum: 20 }
  validates :description, presence: true, length: { maximum: 100 }

  validates :preview_url, presence: true, format: { with: /^(ftp|http|https):\/\/[^ "]+$/, multiline: true, message: "Invalid URL format" }
  validates :stream_link, presence: true, format: { with: /^(ftp|http|https):\/\/[^ "]+$/, multiline: true, message: "Invalid URL format" }
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    game_id = params["game_id"]
    language_id = params["language_id"]
    param_tags = params["tag_id"]

    if !game_id.nil?
      @game = fetch_game_by_id(game_id)
    end

    fetch_langauges()

    tags = fetch_all_tags()

    @option_tags = Array.new
    @selected_tags = Array.new

    if param_tags
      tags.each { |tag|
        if param_tags.include?(tag["id"].to_s)
          @selected_tags.append(tag)
        else
          @option_tags.append([tag["name"], tag["id"]])
        end
      }
    else
      tags.each { |tag|
        @option_tags.append([tag["name"], tag["id"]])
      }
    end

    @live_channels = Array.new
    @offline_channels = Array.new
    
    Channel.all.each { |channel|
      has_tag = @selected_tags.count == 0 || channel.channel_tags.any? { |channel_tag|
        @selected_tags.any? { |selected_tag|
          if selected_tag["forChannel"]
            selected_tag["id"] == channel_tag["tag_id"]
          else
            fetch_games_by_tag_id(selected_tag["id"]).any? { |game|
              channel.channel_game.any?{ |channel_game|
                game["id"] == channel_game["game_id"]
              }
            }
          end
        }
      }

      has_game = game_id.nil? || channel.channel_game.any? { |channel_game|
        channel_game.game_id.to_s == game_id
      }

      if (language_id.nil? || channel.language_id.to_i == language_id.to_i) && has_tag && has_game
      
        preview_status = get_channel_status(channel.preview_statuses)
        if !preview_status.nil?
          channel.p_status = preview_status["id"]
        else
          channel.p_status = 0
        end
        status = get_channel_status(channel.channel_status)

        if !status.nil?
          channel.status = status["id"] 
        else
          channel.status = 3
        end

        if channel.status === 3
          @offline_channels.append(channel)
        else
          @live_channels.append(channel)
        end
      end
    }


    @live_channels = @live_channels.sort_by{|e|
      e.p_status
    }.reverse!

    @offline_channels = @offline_channels.sort_by{|e|
      e.p_status
    }.reverse!
  end

  def show
    @games = Array.new
    @tags = Array.new
    @language = fetch_language_by_id(@channel.language_id)
    @status = get_channel_status(@channel.channel_status)

    latest_preview = @channel.preview_statuses.max_by {|e| e.created_at }

    if !latest_preview.nil? && latest_preview["valid_until"].to_date > Date.today
      @preview = get_channel_status(@channel.preview_statuses)
      @preview_until = latest_preview["valid_until"].getlocal().to_formatted_s(:db)
    end

    @channel.channel_tags.all.each { |x|
      response = HTTParty.get("http://127.0.0.1:10000/tag?id=" + x["tag_id"].to_s)

      if response.code === 200
        tag = JSON.parse(response.body)
      end

      @tags.append(tag)
    }

    @channel.channel_game.all.each { |x|
      response = HTTParty.get("http://127.0.0.1:10000/game?id=" + x["game_id"].to_s)

      game = JSON.parse(response.body)

      @games.append(game)
    }
  end

  def new
    if current_user.channel.nil?
      @channel = Channel.new
      fetch_new_channel_form_data()
    else
      redirect_to channel_url(current_user.channel)
    end
  end

  def edit
    fetch_langauges()
    @Hide_games = true
  end
  
  def create
    tags = channel_params["tags"]
    games = channel_params["games"]

    if !games.nil?
      parsedGames = games.split(',').map(&:to_i)
    end

    @channel = Channel.new(channel_params.except("tags", "games").merge(user_id: current_user.id))
    
    respond_to do |format|
      if @channel.save
        status = ChannelStatus.new(channel_id:@channel.id, status_id: 3)
        status.save

        if !tags.nil?
          tags.each { |tag_id|
            if !tag_id.nil?
              tag = ChannelTag.new(channel_id: @channel.id, tag_id: tag_id.to_i)
              tag.save
            end
          }
        end
        
        if !parsedGames.nil?
          parsedGames.each { |game_id|
            if !game_id.nil?
              game = ChannelGame.new(channel_id: @channel.id, game_id: game_id.to_i)
              game.save
            end
          }
        end

        format.html { redirect_to channel_url(@channel), notice: "Channel was successfully created." }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render :new, json: @channel.errors, status: :unprocessable_entity }
        fetch_new_channel_form_data()
      end
    end
  end


  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to channel_url(@channel), notice: "Channel was successfully updated." }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
        fetch_langauges()
      end
    end
  end


  def destroy
    @channel.destroy

    respond_to do |format|
      format.html { redirect_to channels_url, notice: "Channel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    if current_user.channel.nil? || current_user.channel.id != params[:id].to_i
      redirect_to channels_path, notice: "Not authorized"
    end
  end

  def get_channel_status(channel_status)
    if !channel_status.nil?
      status = channel_status.max_by {|e| e.created_at }

      if !status.nil?
        return fetch_channel_status_by_id(status.status_id)
      end
    end
  end

  def fetch_channel_tags
    response = HTTParty.get("http://127.0.0.1:10000/tag?forChannel=true")

    if response.code === 200
      @tags =JSON.parse(response.body)
    end
  end
  
  def fetch_all_tags
    response = HTTParty.get("http://127.0.0.1:10000/tag")
  
    if response.code === 200
      return JSON.parse(response.body)
    end
  end

  def fetch_games_by_tag_id(tag_id)
    response = HTTParty.get("http://127.0.0.1:10000/game?tagId=" + tag_id.to_s)
  
    if response.code === 200
      return JSON.parse(response.body)["games"]
    end
  end


  def fetch_langauges
    @languages = Array.new
    
    response = HTTParty.get("http://127.0.0.1:10000/language")

    if response.code === 200
      JSON.parse(response.body).each { |langauge|
        @languages.append([langauge["name"], langauge["id"]])
      }
    end
  end
  
  def fetch_language_by_id(id) 
    response = HTTParty.get("http://127.0.0.1:10000/language?id=" + id.to_s )

    if response.code === 200
      return JSON.parse(response.body)
    end
  end

  def fetch_channel_status_by_id(id)
    response = HTTParty.get("http://127.0.0.1:10000/status?id=" + id.to_s )

    if response.code === 200
      return JSON.parse(response.body)
    end
  end

  def fetch_new_channel_form_data    
    @games = Array.new

    fetch_langauges()
    fetch_channel_tags()

    if params["gameSearch"].nil?
      response = HTTParty.get("http://127.0.0.1:10000/game")
      if response.code === 200
        @games = JSON.parse(response.body)["games"]
      end
    else
      response = HTTParty.get("http://127.0.0.1:10000/search?by=game&value=" + params["gameSearch"])
      if response.code === 200
        @games = JSON.parse(response.body)
      end
    end
  end

   
  def fetch_game_by_id(id)
    response = HTTParty.get("http://127.0.0.1:10000/game?id=" + id.to_s)
  
    if response.code === 200
      return JSON.parse(response.body)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def channel_params
      params.require(:channel).permit(:title, :description, :stream_link, :preview_url, :user_id, :language_id, :about, :games, :tags => [])
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_channel.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-image-container">
    <img src=<%= channel.preview_url %> class="card-img-top" alt="...">
  </div>
  <div class="card-body channel-card-body-container">
    <div class="channel-card-description-container">
      <h5 class="card-title">
        <%= channel.title %>
      </h5>
      <p class="card-text" style="text-overflow: ellipsis; max-height: 5px;"> <%= channel.description %></p>
    </div>
    <div class="row mt-1 border-top py-1">
      <div class="col-md-6 box text-start">
        <div>
          <%= link_to "More Info", channel, class:"btn btn-sm btn-outline-secondary" %>
        </div>
      </div>
      <div class="col-md-6 box text-end">
        <div>
          <% if !channel.status.nil? && channel.status == 2 %>
            <%= link_to "Watch Live!", channel.stream_link, class:"btn btn-sm btn-primary", target: :_blank %>
          <% else %>
            <%= button_to "Offline!", {}, class:"btn btn-sm btn-outline-danger",:disabled => true %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/channels/_form.html.erb
<%= form_with(model: channel, data: { controller: "channelForm" } ) do |form| %> 
  <% if channel.errors.any? %>
    <%= render layout: 'shared/error_modal' do %>
      <ul>
        <% channel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    <% end %>
  <% end%>

  <div class="form-group">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Stream Description", style: "display: block" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :stream_link, style: "display: block" %>
    <%= form.text_area :stream_link, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :preview_url, style: "display: block" %>
    <%= form.text_area :preview_url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "About you", style: "display: block" %>
    <%= form.text_area :about, class: "form-control" %>
  </div>

  
  
 <%= form.hidden_field :games, id: "games-input" %> 
  <%if @Hide_games.nil? %>
    <div class="dropdown mt-2">
      <input class="form-control games-search" type="text" id="games-search" placeholder="Click to add Games"> 
      <div id="myDropdown" class="dropdown-content">
      </div>
    </div>
  <div id="games-div" class="my-1 py-2 border-bottom"> </div>
  <%end%>

  <% if !@languages.nil?%>
    <div class="form-group">
      <%= form.label "Stream Language", style: "display: block" %>
      <%= select(:channel, :language_id, options_for_select(@languages, :selected => current_user.channel ? current_user.channel.language_id : 41), { }, { :class => 'form-select' }) %>
    </div>
  <%end%>

  <% if !@tags.nil?%>
    <div class="mb-2 border-bottom">
      <%= form.label "Channel Tags:", style: "display: block" %>
      <% if !@tags.nil? %>
        <% @tags.each do |tag| %>
          <%= form.label tag["name"] %>
          <%= form.check_box :tags, {multiple: true, skip_default_ids: false, class: "form-check-input", }, tag["id"], nil %>  
        <% end %>
      <% end %>
    </div>
  <%end%>


  <div class="mt-3">
    <% if current_page?(new_channel_path) %>
      <%= link_to "Cancel", channels_path, class: "btn btn-outline-primary" %>
    <% else %>
      <%= link_to "Cancel", @channel, class: "btn btn-outline-primary" %>
    <% end %>
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/channels/edit.html.erb
<div class='card'>
  <div class="card-header">
    <h4>Edit channel</h4>
  </div>
  <div class="card-body">
    <%= render "form", channel: @channel %>
  </div>
</div>

app/views/channels/index.html.erb
<div id="channels", data-controller="channels">
  <div class="mb-2">
    <label>Language</label>
    <%= select(
      {},
      {},
      options_for_select(@languages ,:selected => params[:language_id].to_i,  ),
      { :include_blank => true },
      { :id => "language-select" }
    ) %>

    
    <label>Tags</label>
    <%= select(
      {},
      {},
      options_for_select(@option_tags  ),
      { :include_blank => true },
      { :id=>"tags-select" }
    ) %>
  </div>

  <span id="tags-container">
    <% @selected_tags.each do |tag|%>
      <span
        id=<%= tag['id']%>
        class="badge rounded-pill text-bg-primary tag-badge"
      >
        <%= tag["name"]%> X
      </span>
    <%end%>
  </span>

  <div class="row justify-content-md-start gy-2 mb-4">
   <% if !@game.nil? %>
    <h1>Streamers who stream: <%= @game["name"]%></h1>
   <%end%>
    <% @live_channels.each do |channel| %>
      <div class="col-md-3">
        <%= render channel %>
      </div>
    <% end %>
     <% @offline_channels.each do |channel| %>
      <div class="col-md-3">
        <%= render channel %>
      </div>
    <% end %>
  </div>
</div>

app/views/channels/new.html.erb
<div class='card'>
  <div class="card-header">
    <h4>New channel</h4>
  </div>
  <div class="card-body">
    <%= render "form", channel: @channel %>
  </div>
</div>

app/views/channels/show.html.erb
<div class="card channelDetail">
  <div class="crop">
    <img src=<%= @channel.preview_url %> class="card-img-top" alt="...">
  </div>
  <div class="card-body">
    <h3 class="card-title">
      <%=@channel.title%>
    </h3>
    <p>
      Streamer Name
    <p>
    <p> <%= @channel.description %></p>
    
    <h4>About Streamer</h4>
    <p class="card-text"><%= @channel.about%></p>

    <span>Stream language: <%= @language["name"]%></span>

    <h4 class="border-bottom mb-2">
      Games
    </h4>
    <div class="border-bottom mb-3">
      <% @games.each do |item| %>
          <%= link_to item['name'], root_path(:game_id=> item["id"]), class:"mx-2" %>
      <% end %>
    </div>

    <% if @channel.user == current_user && !@preview.nil? && @preview %> 
      <p style="font-weight: bold;">
        <%= @preview["label"] %>
          until:
        <%= @preview_until %>
      </p>
    <%end%>

    <% if !@tags.nil? %>
      <div class="border-bottom mb-3">
        <% @tags.each do |item| %>
            <%= link_to item['name'], root_path(["tag_id[]"] => item["id"]), class:"mx-2" %>
        <% end %>
      </div>
    <% end %>

    <div class="row">
      <div class="col-md-8 box text-start">
        <% if @channel.user == current_user %> 
          <div class="row">
            <div class="col">
              <%= link_to "Edit", edit_channel_path(@channel), class:"btn btn-sm btn-outline-secondary" %>
            </div>
            <div  class="col">
              <%= link_to "Manage Games", new_channel_game_path, class:"btn btn-sm btn-outline-primary" %>
            </div>
            <div  class="col">
              <%= link_to "Manage Tags", new_channel_tag_path, class:"btn btn-sm btn-outline-primary" %>
            </div>
            <% if @preview.nil? || @preview["id"] != 1%> 
              <div class="col">
                <%= link_to "Order Premium!", new_preview_status_path, class:"btn btn-sm btn-primary" %>
              </div>
            <%end %>
          </div>
        <%end%>
      </div>
      <div class="col-md-4 box text-end">
        <div>
          <% if @channel.user != current_user %>
             <% if @status.nil? || @status["id"] != 2 %>
              <%= button_to "Offline", {}, class:"btn btn-sm btn-outline-danger", :disabled => true %>
            <% else %>
              <%= link_to "Watch Live!", @channel.stream_link, class:"btn btn-sm btn-primary", target: :_blank %>
            <% end %>
          <% else %>
            <% if @status.nil? || @status["id"] != 2 %>
              <%= button_to "Go Live!", { :controller => 'channel_statuses', :channel_id => @channel.id, :status_id => 2}, :method => :post, class: "btn btn-sm btn-success" %> 
            <% else %>
              <%= button_to "Go Offline!", { :controller => 'channel_statuses', :channel_id => @channel.id, :status_id => 3}, :method => :post, class: "btn btn-sm btn-danger" %> 
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>