config/routes.rb
Rails.application.routes.draw do
  resources :channel_tags
  resources :preview_statuses
  resources :channel_statuses
  resources :channel_games
  get 'games/index'
  devise_for :users
  resources :channels
  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
  end

  root 'channels#index'
end

app/models/channel_game.rb
class ChannelGame < ApplicationRecord
  belongs_to :channel
  attr_accessor :games
end

app/controllers/channel_games_controller.rb
class ChannelGamesController < ApplicationController
  before_action :set_channel_game, only: %i[ show edit update destroy ]

  def new
    @channel_game = ChannelGame.new

    response = HTTParty.get("http://127.0.0.1:10000/game")
    
    @games = Array.new

    current_games = current_user.channel.channel_game

    if !current_user.channel.channel_game.nil?
      current_user.channel.channel_game.each { |channel_game|
        game = fetch_game_by_id(channel_game["game_id"])
        game["channel_game_id"] = channel_game["id"]
        @games.append(game)
      }
    end

    if response.code == 200 
      @options = JSON.parse(response.body)["games"]
    else
      flash[:alert] = "Error fetching games <br /> #{response.message}".html_safe
    end
  end

  def index

  end

  def create
    @channel_game = ChannelGame.new(channel_id: current_user.channel.id, game_id: channel_game_params["game"])
    @channel_game.save
  end

  def has_game(id)
    return !!current_user.channel.channel_game.find { |each| each.game_id.to_i == id.to_i }
  end

  def redd
    redirect_to  new_channel_game_path
  end

  def destroy
    @channel_game.destroy

    redirect_to  new_channel_game_path
  end
  
  def fetch_game_by_id(id)
    response = HTTParty.get("http://127.0.0.1:10000/game?id=" + id.to_s)
  
    if response.code === 200
      return JSON.parse(response.body)
    end
  end

  private
    def set_channel_game
      @channel_game = ChannelGame.find(params[:id])
    end

    def channel_game_params
      params.permit(:game)
    end
end

app/helpers/channel_games_helper.rb
module ChannelGamesHelper
end

app/views/channel_games/_form.html.erb
<%= form_with(model: channel_game, data: { controller: "channelGame", games: @current_user.channel.channel_game, token: session[:_csrf_token] } ) do |form| %>


  <% if channel_game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(channel_game.errors.count, "error") %> prohibited this channel_game from being saved:</h2>

      <ul>
        <% channel_game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="games-tags" id="channel-game-tags">
    <% @games.each do |game|%>
      <%= button_to game["name"] + " X", channel_game_path(game['channel_game_id']), method: :delete, id:game["id"],  class:"badge rounded-pill text-bg-primary tag-badge no-border mx-1"  %>
    <%end%>
  </div>

  <div class="dropdown mt-2">
    <input class="form-control games-search" type="text" id="channel-games-search" placeholder="Click to add Games"> 
    <div id="games-dropdown" class="dropdown-content">
    </div>
  </div>


  <div class="mt-2">
    <%= link_to "Back", channel_path(current_user.channel), class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/channel_games/new.html.erb
<h1 class="text-center mb-4">Manage channel games</h1>

<%= render "form", channel_game: @channel_game %>