config/routes.rb
Rails.application.routes.draw do
  resources :channel_tags
  resources :preview_statuses
  resources :channel_statuses
  resources :channel_games
  get 'games/index'
  devise_for :users
  resources :channels
  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
  end

  root 'channels#index'
end

app/views/layouts/_alerts.html.erb
<div class="custom-alert alert alert-danger alert-dismissible fade show " role="alert">
<%= alert %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-right navbar-dark navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <%= link_to 'Streams', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'Games', games_index_path, class: "nav-link" %>
            </li>
            <% if current_user %>
              <li class="nav-item">
                <span class="nav-link"><%= current_user.email%> <span>
              </li>
            <% end%>
      </ul>
      <div class="navbar-nav nav navbar-right">
      <% if !user_signed_in? %> 
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
            </li>
            |
            <li class="nav-item">
              <%= link_to 'Login', new_user_session_path, class: "nav-link" %>
            </li>
          <% else %> 
            <li class="nav-item px-5">
              <% if current_user.channel %>
                <%= link_to 'My channel', current_user.channel, class: "nav-link" %>
              <% else %>
                <%= link_to 'My channel', new_channel_path, class: "nav-link" %>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, data: { "turbo-method": :delete }, class: "nav-link" %>
            </li>
          <% end %>
      </div>
  </div>
    </div>
  </div>
</nav>

app/views/layouts/_notices.html.erb
<% if alert %>
  <div class="custom-notification alert alert-success alert-dismissible fade show" role="alert">
<% else %>
  <div class="custom-alert alert alert-success alert-dismissible fade show" role="alert">
<% end %>
<%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby MVC</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <% if alert %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <% if notice %>
          <%= render 'layouts/notices'%>
      <% end %> 
      <br/>

      <%= yield %>
      <br />
      <br />
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>